name: Node.js CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: volta-cli/action@v1
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: ls -la
      - run: npm test
      - run: npm run build --if-present
        env:
          CI: true
